module.exports = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  GET_TRANSACTION_SUCCESS: 'GET_TRANSACTION_SUCCESS',
  GET_TRANSACTION_FAILED: 'GET_TRANSACTION_FAILED',
  FIND_CUSTOMER: 'FIND_CUSTOMER',
  GET_CONTACT_LIST: 'GET_CONTACT_LIST',
  CREATE_CONTACT: 'CREATE_CONTACT',
  SET_EDIT_CONTACT_FORM: 'SET_EDIT_CONTACT_FORM',
  RESET_EDIT_CONTACT_FORM: 'RESET_EDIT_CONTACT_FORM',
  DELETE_CONTACT: 'DELETE_CONTACT',
  GET_LIST_DEBIT: 'GET_LIST_DEBIT',
};
