module.exports = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  GET_TRANSACTION_SUCCESS: 'GET_TRANSACTION_SUCCESS',
  GET_TRANSACTION_FAILED: 'GET_TRANSACTION_FAILED',
  FIND_CUSTOMER: 'FIND_CUSTOMER',
};
